### ISSUE TITLE
html sections

### ISSUE THREAD

**Issue by rimmesbe** [Teebrain/prj-rev-bwfs-dasmoto#1]
So one principle in html is that an elements opening or closing tag (`<div> </div>`) will never split another elements opening and closing tag. Right now you have the h2 element open, then the div open, then the h2 close, then the div close. Think of tags like nesting dolls, the child element must close before the parent element can close. 
Also the div should be wrapped around the h2 (parent) not the other way around.
<img width="122" alt="screen shot 2017-06-28 at 1 57 34 pm" src="https://user-images.githubusercontent.com/9957628/34223384-28274a0a-e58d-11e7-9050-a903e2f58f91.png">

https://github.com/Teebrain/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L10-L14

**Comment by Teebrain** [comment]
Thank you for the correction
