### ISSUE TITLE
spans vs divs

### ISSUE THREAD

**Issue by rimmesbe** [Teebrain/prj-rev-bwfs-dasmoto#2]
You don't want to use a div here to wrap this inline text. Div's are used for organizing other elements by wrapping them together. A `<span>` would be a good choice because spans are an inline tag that can be used to wrap snippets of text inside of other elements, like p-tag.

https://github.com/Teebrain/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L13

**Comment by Teebrain** [comment]
Thank you for the correction i just made the changes..
