### ISSUE TITLE
setting page font

### ISSUE THREAD

**Issue by rimmesbe** [Teebrain/prj-rev-bwfs-dasmoto#3]
Right now you are setting the font-family is almost every selector, which is inefficient. Instead we can set the default font-family for all the elements on the page by using inheritance:
html { font-family: Helvetica; }
Now all elements will default to this font.

https://github.com/Teebrain/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/style.css#L4

**Comment by Teebrain** [comment]
Thank you for the correction i just made the changes..
