### ISSUE TITLE
the purpose of css classes

### ISSUE THREAD

**Issue by rimmesbe** [Teebrain/prj-rev-bwfs-dasmoto#4]
The purpose of CSS classes is to be a reusable source of set styling. Your price1, price2, price3 classes all have the same styling, so why not just use one ".price" class that they all share. This will be a lot more efficient because you don't have to write the same styling 3 times.

https://github.com/Teebrain/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/style.css#L18-L22

**Comment by Teebrain** [comment]
Thank you for the correction i just made the changes..
