### ISSUE TITLE
refactor that CSS

### ISSUE THREAD

**Issue by rimmesbe** [Teebrain/prj-rev-bwfs-dasmoto#5]
Look at all your h2 stylings (#brush, #paint, etc). 
They all have pretty much the same styling except for the background color. You should extract all that shared styling to one selector, in this case maybe h2 { }
but in other cases maybe create a new class for them all to share. Remember that html elements can have more than one class.

https://github.com/Teebrain/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/style.css#L12-L15

**Comment by Teebrain** [comment]
thanks just made the correct changes
