### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [Teebrain/prj-rev-bwfs-dasmoto#6]
Grade: Needs improvement

Summary: You have a good start to this project and your instincts are in the right place. I like that you went to split the html up into sections, but right now it is kind of a mess and needs to be reorganized. Take a look at the issues I created as they will point out some code that needs to be fixed or optimized. Projects are going to be getting a lot larger and the key to handling that is organization and efficient styling. Here is a good article with some examples: 
https://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by Teebrain** [comment]
thanks for the tip and correction, i made updates to it and will like to know if am right this time thank you..
